name: Add to Contributors
on:
  push:
    branches:
    - master

jobs:
  checkFirst:
    runs-on: ubuntu-latest
    outputs:
      first: ${{steps.contri.outputs.FIRST}}
      user: ${{steps.contri.outputs.USER}}
    steps:
    - name: Check first PR of user
      id: contri
      uses: theSwapnilSaste/first-interaction@main
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        pr-message: 'Adding this ${{ github.event.pull_request.user.login }} to Contributors...'

  addToContributors:
    runs-on: ubuntu-latest
    needs: checkFirst
    steps:
    - name: Test Add to README.md
      uses: actions/checkout@v2
    - if: ${{needs.checkFirst.outputs.first}} == 'true'
      run: |
          echo ${{needs.checkFirst.outputs.first}}
          echo -n "${{needs.checkFirst.outputs.user}}" >> README.md
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push
