name: Add to Contributors
on:
  push:
    branches:
    - master

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
    - name: Check first PR of user
      id: contri
      uses: theSwapnilSaste/first-interaction@main
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        pr-message: 'Adding this ${{ github.event.pull_request.user.login }} to Contributors...'
    - name: Test Add to README.md
      uses: actions/checkout@v2
    - if: steps.id.contri.outputs.FIRST=='true'
      run: |
          github.event.pull_request.user.login > README.md
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push
