name: Add to Contributors
on:
  push:
    branches:
    - master

jobs:
  checkFirst:
    runs-on: ubuntu-latest
    outputs:
      first: ${{steps.contri.outputs.FIRST}}
      user: ${{steps.contri.outputs.USER}}
    steps:
    - name: Check first PR of user
      id: contri
      uses: theSwapnilSaste/first-interaction@main
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        pr-message: 'Adding this ${{ github.event.pull_request.user.login }} to Contributors...'

# # jobs:
#   job1: 
#     runs-on: ubuntu-latest
#   # Map a step output to a job output
#     outputs:
#       output1: ${{steps.step1.outputs.test}}
#       output2: ${{steps.step2.outputs.test}}
#     steps:
#       - id: step1
#         run: echo"::set-output name=test::hello"
#       - id: step2
#         run: echo"::set-output name=test::world"

#   job2: 
#     runs-on: ubuntu-latest
#     needs: job1
#     steps:
#       - id: ab
#         run: echo${{needs.job1.outputs.output1}}${{needs.job1.outputs.output2}}


  addToContributors:
    runs-on: ubuntu-latest
    needs: checkFirst
    steps:
    - name: Test Add to README.md
      uses: actions/checkout@v2
    - if: steps.id.contri.outputs.FIRST!='true'
      run: |
          echo ${{needs.checkFirst.outputs.first}}
          echo "${{needs.checkFirst.outputs.first}}"
          echo ${{ steps.id.contri.outputs.USER }} >> README.md
          echo "${{ steps.id.contri.outputs.USER }}"
          echo ${{ steps.id.contri.outputs.USER }}                    
          echo "steps.id.contri.outputs.USER" >> README.md
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push
