name: Add to Contributors on first PR
on:
  push:
    branches:
    - master

jobs:
  checkFirst:
    runs-on: ubuntu-latest
    outputs:
      isFirst: ${{steps.contribution.outputs.FIRST}}
      username: ${{steps.contribution.outputs.USER}}
    steps:
    - name: Check if the pull-request of the author
      id: contribution
      uses: theSwapnilSaste/first-interaction@main
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        pr-message: 'Congratulations @${{ github.event.pull_request.user.login }} on your first pull request being merged to project. You will be added to the contributors list in a while. Thank you :smile: '

  addToContributors:
    if: needs.checkFirst.outputs.isFirst == 'false'
    runs-on: ubuntu-latest
    needs: checkFirst
    steps:
    - name: Test Add to README.md
      uses: actions/checkout@v2
    - if: needs.checkFirst.outputs.isFirst == 'false'
      run: |
          echo ${{needs.checkFirst.outputs.first}}
          echo '\n${{needs.checkFirst.outputs.username}}\n' >> README.md
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push
