name: "Pull Request Labeler"
on: 
# Trigger the workflow on push or pull request,
# but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: theSwapnilSaste/labeler@master
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
