name: Welcome
on:
  issues:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
      repo-token: ${{ secrets.GITHUB_TOKEN }}
      issue-message: 'Welcome to the team mate, I am just here to welcome you, someone will address your issue soon...'
      pr-message: 'Your code looks fine, However as this is your first PR, do read and follow how to write a good PR message.'
